### ISSUE TITLE
Patcher Request - Sound consistency patcher using ISC and AOS

### ISSUE THREAD

**Issue by ixanza** [Synthesis-Collective/Development#1]
A patcher that if it detects Audio overhaul Skyrim or immersive sounds compendium to assign proper sound keywords to them.

This is not the entirety of records but covers a large portion of weapons and armour

**__Requires Immersive Sound Compendium__**

**Keyword = ClothingRing: **
Add YNAM - Sound PIckup - ITMRingUp XX08AB14 (ISC)

**Keyword = ClothingNecklace: **
Add YNAM - Sound Pickup  - ITMNeckUp XX08AB15 and ZNAM - Sound Putdown - ITMNeckDown XX08AB16. (ISC)
IF Exists ITMClothingUp - 003E879 and ITMClothingDown - 003E909, replace with ITMNeckUp and NeckDown respectively

**Keyword = WeapTypeBattleAxe: **
Replace TNAM - Attack Fail Sound - WPNSwing2Hand 000E4CAC with  WPNSwingAxe2Hand XXA1E6B31 (ISC)

**Keyword = WeapMaterialWarhammer:**
Replace  TNAM - Attack Fail Sound - WPNSwing2Hand 000E4CAC with WPNSwingBlunt2Hand XX1F5E3B (ISC)

**__Requires Audio Overhaul Skyrim__**

**Keyword = WeapMaterialDagger: **
Replace INAM - Impact Data Set  : WPNzBlade1HandImpactSet  00013CAC with WPNzBlade1HandSmallImpactSet XX05B6EA (AOS)
Replace NAM9 - Equip Sound : WPNBlade1HandDrawSD 0003C72E with WPNBlade1HandSmallDrawSD 0003CED9
Replace NAM8 - Unequip Sound : WPNBlade1HandSheathSD 0003C72F with WPNBlade1HandSmallSheathSD 0003CED8

**Comment by tr4wzified** [comment]
Done

https://github.com/tr4wzified/AOSISCSoundPatcher

**Comment by tr4wzified** [comment]
Closing since it's done already
