### ISSUE TITLE
Port Patcher - reading is good

### ISSUE THREAD

**Issue by mrudat** [Synthesis-Collective/Development#10]
the original: https://github.com/vabatta/zedit-patcher-mod-reading-is-good

some updates: https://github.com/mrudat/zedit-patcher-mod-reading-is-good

**Comment by theSkyseS** [comment]
Done! Should work:
https://github.com/theSkyseS/ReadingIsGoodLegacy

**Comment by tr4wzified** [comment]
Nice job :)
