### ISSUE TITLE
Patcher Request - change every single Firewood pile into the container version, even the ones added by other mods, so no patch is required. 

### ISSUE THREAD

**Issue by BuddyKidd** [Synthesis-Collective/Development#24]
Like the one in this mod: https://www.nexusmods.com/skyrimspecialedition/mods/35059

**Comment by halgari** [comment]
Implemented : https://github.com/Synthesis-Collective/MakeFirewoodPilesIntoContainers/blob/main/MakeFirewoodPilesIntoContainers/Program.cs
