### ISSUE TITLE
Patcher Request - NPC Stat Rescaler

### ISSUE THREAD

**Issue by Althro** [Synthesis-Collective/Development#25]
A Synthesis/Mutagen version of this would be awesome: https://www.nexusmods.com/skyrimspecialedition/mods/24254

It's currently zEdit based and made by the same author as Know Your Enemy/Know Your Armor. 

If either a config json or gui based solution could be included that would be awesome as the main selling point of the mod/z-Edit script is it's ability to be customized.

**Comment by theSkyseS** [comment]
Done
https://github.com/theSkyseS/NPCStatRescaler

**Comment by Althro** [comment]
I can confirm this works rather nicely 😸
