### ISSUE TITLE
Patcher Request - Harvest Those Mammoth Skulls

### ISSUE THREAD

**Issue by DokuseiSan** [Synthesis-Collective/Development#26]
A script for Harvest Those Mammoth Skull would be sweet. I love to do it myself, but I don't really have the time to do it.

The mod page: https://www.nexusmods.com/skyrimspecialedition/mods/48551

**Comment by theSkyseS** [comment]
will be done

**Comment by halgari** [comment]
@theSkyseS patcher looks to be almost a clone of the one for : https://github.com/Synthesis-Collective/Development/issues/24 if you haven't already you might be able to just copy/paste the code and update the Formkeys

**Comment by theSkyseS** [comment]
Done? https://github.com/Synthesis-Collective/MakeFirewoodPilesIntoContainers/pull/1
@halgari i decided to PR this to your patcher. Can make it standalone if you want.

**Comment by theSkyseS** [comment]
Now is standalone 
https://github.com/theSkyseS/HarvestThoseMammothSkulls
