### ISSUE TITLE
Patcher Request - UPF Cell Encounter Level in Name Patcher

### ISSUE THREAD

**Issue by monkeyangie** [Synthesis-Collective/Development#45]
A synthesis patch for this zEdit script https://www.nexusmods.com/skyrimspecialedition/mods/13542

thank you :)

**Comment by mrudat** [comment]
https://github.com/Deigue/CellEncounterLevelsInName <-- already exists

**Comment by monkeyangie** [comment]
thank you! i missed for some reason 👍
