### ISSUE TITLE
Patcher Request: Journal Quest Limit Recover

### ISSUE THREAD

**Issue by Fuzzlesz** [Synthesis-Collective/Development#55]
wSkeever included an xedit script to add support for mod-added quests.  Skeever asked that I submit this to see if anyone would do a Synthesis version, as he's not super familiar.

https://www.nexusmods.com/skyrimspecialedition/mods/56130

**Comment by radj307** [comment]
I was just thinking about making a Synthesis patcher for that, I'll take a look but may need more information on what exactly needs to be implemented

**Comment by Fuzzlesz** [comment]
wSkeever tends to reside in https://discord.gg/G8PZhgTN the r/skyrimmods server, I'm sure you can go bug him if you have questions lol

**Comment by radj307** [comment]
Done
https://github.com/radj307/Quest-Journal-Limit-Fixer
