### ISSUE TITLE
Too many masters in big modlists - potential simple solution

### ISSUE THREAD

**Issue by Sirgilly** [Synthesis-Collective/Development#67]
Hi,

I am finding I cant use the patcher as there are too many masters. I noticed Item weight customizer allows you to get around this by having items be selectable. This actually allows you to run the patcher twice, once for books and notes perhaps and then again for other misc items. Perhaps a couple of setting here to run for weapons and spells separately?

Sirgilly

**Comment by Noggog** [comment]
Yup!  That's one solution ala
https://github.com/Mutagen-Modding/Synthesis/discussions/300

It sounds like you have a specific patcher in mind that these style settings should be added to?  I'd recommend making this issue on the github page for that specific patcher, as it'll likely be noticed easier by the related parties there

**Comment by Sirgilly** [comment]
ok ill reach out to them. thanks
