### ISSUE TITLE
Patcher Request - Support for Training Dummies and Targets SSE

### ISSUE THREAD

**Issue by mrudat** [Synthesis-Collective/Development#8]
Original mod ([LE](https://www.nexusmods.com/skyrim/mods/23698)|[SE](https://www.nexusmods.com/skyrimspecialedition/mods/41967))

Discussion: https://discord.com/channels/759302581448474626/811636352801308772/821778469834063935

**Comment by tr4wzified** [comment]
I can probably whip this one up soon

**Comment by tr4wzified** [comment]
https://github.com/m-vlad/LootableThings-TrainingDummies-Patcher
Already done
